const { Events, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle, MessageFlags } = require('discord.js');
const Database = require('better-sqlite3');
const fs = require('fs'); const path = require('path');
const client = global.__KIND_BOSS_CLIENT;
const CREATE_CHANNEL = process.env.INTRO_CREATE_CHANNEL_ID || '1556383760209944586';
const VIEW_CHANNEL = process.env.INTRO_VIEW_CHANNEL_ID || '1555985898615734414';
const DATA_DIR = process.env.PERSISTENT_DATA_DIR || process.env.DATA_DIR || '/app/data';
try { fs.mkdirSync(DATA_DIR,{recursive:true}); } catch {}
const db = new Database(path.join(DATA_DIR,'player-intros.db'));
db.exec(`CREATE TABLE IF NOT EXISTS intros(user_id TEXT PRIMARY KEY,minecraft_username TEXT NOT NULL,preferred_name TEXT,creator_name TEXT,youtube TEXT,content TEXT,about TEXT,fun_fact TEXT,message_id TEXT,updated_at INTEGER NOT NULL);`);
const eph=(i,c)=>i.replied||i.deferred?i.followUp({content:c,flags:MessageFlags.Ephemeral}):i.reply({content:c,flags:MessageFlags.Ephemeral});
function panel(){return new EmbedBuilder().setTitle('👋 KIND SMP Player Intros').setDescription('Introduce yourself to the SMP!\n\nPress **Create / Edit My Intro** and fill out the form. Your **Minecraft username is required** so KIND BOSS can show your Minecraft face and give members quick access to your NameMC profile.\n\nYou can come back anytime and edit your intro.');}
function row(){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('intro:edit').setLabel('Create / Edit My Intro').setEmoji('👤').setStyle(ButtonStyle.Primary));}
function modal(old={}){return new ModalBuilder().setCustomId('intro:submit').setTitle('Your KIND SMP Intro').addComponents(
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('mc').setLabel('Minecraft username (required)').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(16).setValue(old.minecraft_username||'')),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('name').setLabel('Preferred name / creator name').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(80).setValue(old.preferred_name||old.creator_name||'')),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('youtube').setLabel('YouTube channel or creator link (optional)').setStyle(TextInputStyle.Short).setRequired(false).setMaxLength(200).setValue(old.youtube||'')),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('content').setLabel('What content / Minecraft stuff do you enjoy?').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(500).setValue(old.content||'')),
 new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('about').setLabel('About you + a fun fact').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(900).setValue([old.about,old.fun_fact].filter(Boolean).join('\n')||''))
 );}
function introEmbed(user,row){const mc=row.minecraft_username; const namemc=`https://namemc.com/profile/${encodeURIComponent(mc)}`; const head=`https://mc-heads.net/avatar/${encodeURIComponent(mc)}/128`;
 const e=new EmbedBuilder().setTitle(`👋 Meet ${row.preferred_name || user.username}!`).setDescription(`🎮 **Minecraft:** [${mc}](${namemc})\n${row.youtube?`📺 **Creator / YouTube:** ${row.youtube}\n`:''}\n🎥 **Content & Minecraft interests**\n${row.content}\n\n💬 **About Me**\n${row.about}`).setThumbnail(head).setFooter({text:`Discord: @${user.username} • Minecraft skin from username`}).setTimestamp(new Date(row.updated_at)); return e;}
async function ensurePanel(){const ch=await client.channels.fetch(CREATE_CHANNEL).catch(()=>null);if(!ch?.isTextBased())return console.warn('[Intros] Create channel unavailable');const msgs=await ch.messages.fetch({limit:50}).catch(()=>null);let msg=msgs&&[...msgs.values()].find(m=>m.author.id===client.user.id&&m.components?.some(r=>r.components?.some(c=>c.customId==='intro:edit')));if(msg)await msg.edit({embeds:[panel()],components:[row()]});else await ch.send({embeds:[panel()],components:[row()]});}
client.once(Events.ClientReady,()=>{ensurePanel().catch(console.error);console.log(`[Intros] Ready. DB: ${path.join(DATA_DIR,'player-intros.db')}`);});
client.on(Events.InteractionCreate,async i=>{try{
 if(i.isButton()&&i.customId==='intro:edit'){const old=db.prepare('SELECT * FROM intros WHERE user_id=?').get(i.user.id)||{};return i.showModal(modal(old));}
 if(i.isModalSubmit()&&i.customId==='intro:submit'){const mc=i.fields.getTextInputValue('mc').trim();if(!/^[A-Za-z0-9_]{3,16}$/.test(mc))return eph(i,'❌ Enter a valid Java Minecraft username (3–16 letters, numbers, or underscores).');const preferred=i.fields.getTextInputValue('name').trim(),youtube=i.fields.getTextInputValue('youtube').trim(),content=i.fields.getTextInputValue('content').trim(),about=i.fields.getTextInputValue('about').trim(),now=Date.now();let old=db.prepare('SELECT * FROM intros WHERE user_id=?').get(i.user.id);const view=await client.channels.fetch(VIEW_CHANNEL).catch(()=>null);if(!view?.isTextBased())return eph(i,'❌ The intro viewing channel is unavailable. Please tell staff.');const data={minecraft_username:mc,preferred_name:preferred,youtube,content,about,updated_at:now};let msg=old?.message_id?await view.messages.fetch(old.message_id).catch(()=>null):null;const embed=introEmbed(i.user,data);if(msg)await msg.edit({embeds:[embed]});else msg=await view.send({embeds:[embed]});db.prepare(`INSERT INTO intros(user_id,minecraft_username,preferred_name,creator_name,youtube,content,about,fun_fact,message_id,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET minecraft_username=excluded.minecraft_username,preferred_name=excluded.preferred_name,youtube=excluded.youtube,content=excluded.content,about=excluded.about,message_id=excluded.message_id,updated_at=excluded.updated_at`).run(i.user.id,mc,preferred,preferred,youtube,content,about,'',msg.id,now);return eph(i,old?'✅ Your intro was updated!':'✅ Your intro was posted!');}
 }catch(e){console.error('[Intros] interaction error',e);if(i.isRepliable())eph(i,'❌ Something went wrong. Check Railway logs.').catch(()=>{});}});
