const { Events, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle, UserSelectMenuBuilder, StringSelectMenuBuilder, ChannelType, PermissionFlagsBits, MessageFlags } = require('discord.js');
const Database = require('better-sqlite3');
const { DateTime } = require('luxon');
const client = global.__KIND_BOSS_CLIENT;

const GUILD_ID=process.env.GUILD_ID;
const CONTROL=process.env.APPLICATION_CONTROL_CHANNEL_ID;
const REVIEW=process.env.APPLICATION_REVIEW_CHANNEL_ID;
const INTERVIEW=process.env.INTERVIEW_ROOM_CHANNEL_ID;
const FINAL=process.env.FINAL_APPROVAL_CHANNEL_ID;
const APP_CATEGORY=process.env.STAFF_APPLICATIONS_CATEGORY_ID;
const COMMUNITY=process.env.COMMUNITY_CATEGORY_ID;
const ANNOUNCE=process.env.ANNOUNCEMENTS_CHANNEL_ID;
const SMP=process.env.SMP_MEMBER_ROLE_ID;
const GENERAL=process.env.GENERAL_STAFF_ROLE_ID;
const HEAD_GENERAL=process.env.HEAD_GENERAL_STAFF_ROLE_ID;
const SENIOR=process.env.SENIOR_STAFF_ROLE_ID;
const HEAD_SENIOR=process.env.HEAD_SENIOR_STAFF_ROLE_ID;
const COOWNER=process.env.CO_OWNER_ROLE_ID;
const OWNER=process.env.OWNER_ROLE_ID;

const RANKS=[
  {key:'general',label:'General Staff',role:GENERAL},
  {key:'head_general',label:'Head of General Staff',role:HEAD_GENERAL},
  {key:'senior',label:'Senior Staff',role:SENIOR},
  {key:'head_senior',label:'Head Senior Staff',role:HEAD_SENIOR},
  {key:'co_owner',label:'Co-Owner',role:COOWNER},
  {key:'owner',label:'Owner',role:OWNER},
];
const db=new Database(process.env.STAFF_APPLICATIONS_DB_PATH||'./data/staff-applications.db');
db.exec(`CREATE TABLE IF NOT EXISTS staff_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS staff_apps(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,target_rank TEXT NOT NULL,source TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'submitted',answers TEXT NOT NULL DEFAULT '{}',score INTEGER,notes TEXT,review_message_id TEXT,voice_channel_id TEXT,final_message_id TEXT,announce_ts INTEGER,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS staff_approvals(app_id INTEGER NOT NULL,staff_id TEXT NOT NULL,role_kind TEXT NOT NULL,PRIMARY KEY(app_id,staff_id));`);
const setting=(k,d='')=>db.prepare('SELECT value FROM staff_settings WHERE key=?').get(k)?.value??d;
const setSetting=(k,v)=>db.prepare('INSERT INTO staff_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v));
if(!setting('open')) setSetting('open','0');
const appById=id=>db.prepare('SELECT * FROM staff_apps WHERE id=?').get(id);
const rank=k=>RANKS.find(r=>r.key===k);
const has=(m,id)=>!!id&&m?.roles?.cache?.has(id);
const leadership=m=>has(m,OWNER)||has(m,COOWNER);
const seniorPlus=m=>leadership(m)||has(m,HEAD_SENIOR)||has(m,SENIOR);
const eph=(i,c)=>i.replied||i.deferred?i.followUp({content:c,flags:MessageFlags.Ephemeral}):i.reply({content:c,flags:MessageFlags.Ephemeral});
async function text(id){const c=await client.channels.fetch(id).catch(()=>null);return c?.isTextBased()?c:null;}
function currentRank(m){for(const r of [...RANKS].reverse()) if(has(m,r.role)) return r.key;return has(m,SMP)?'member':null;}
function normalTargets(m){const c=currentRank(m); if(c==='member')return ['general']; if(c==='general')return ['head_general','senior']; if(c==='head_general')return ['senior']; if(c==='senior')return ['head_senior']; if(c==='head_senior')return ['co_owner']; if(c==='co_owner')return ['owner']; return [];}
function panel(){return new EmbedBuilder().setTitle('🛡️ KIND SMP Staff Applications').setDescription(`**Status:** ${setting('open')==='1'?'🟢 Open':'🔴 Closed'}\n\nOpen/close public applications or start a leadership **Direct Interview** for a specific member.`);}
function panelRows(){return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('sa:open').setLabel('Open Applications').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('sa:close').setLabel('Close Applications').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('sa:direct').setLabel('Direct Interview').setStyle(ButtonStyle.Primary))];}
async function ensureControl(){const c=await text(CONTROL);if(!c)return;const ms=await c.messages.fetch({limit:50}).catch(()=>null);const old=ms?.find(m=>m.author.id===client.user.id&&m.components.some(r=>r.components.some(x=>x.customId==='sa:open')));if(old)return old.edit({embeds:[panel()],components:panelRows()});return c.send({embeds:[panel()],components:panelRows()});}
async function deletePublic(){const id=setting('public_channel');if(id){const c=await client.channels.fetch(id).catch(()=>null);if(c)await c.delete('Staff applications closed').catch(()=>null);}setSetting('public_channel','');}
async function openPublic(g){let c=setting('public_channel')?await g.channels.fetch(setting('public_channel')).catch(()=>null):null;if(!c)c=await g.channels.create({name:'📋・staff-applications',type:ChannelType.GuildText,parent:COMMUNITY,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:SMP,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory],deny:[PermissionFlagsBits.SendMessages]},{id:GENERAL,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory],deny:[PermissionFlagsBits.SendMessages]},{id:SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory],deny:[PermissionFlagsBits.SendMessages]},{id:OWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory]}]});setSetting('public_channel',c.id);await c.send({embeds:[new EmbedBuilder().setTitle('🛡️ Staff Applications Are Open').setDescription('SMP Members may apply for **General Staff**. Existing staff may apply for an eligible higher rank.\n\nA higher rank means **more responsibility and trust**, not more freedom or power.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('sa:apply').setLabel('Apply for Staff / Promotion').setStyle(ButtonStyle.Success))]});return c;}
function targetMenu(id,keys,direct=false){return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`sa:target:${id}:${direct?'direct':'normal'}`).setPlaceholder('Choose target rank').addOptions(keys.map(k=>({label:rank(k).label,value:k}))));}
function appModal(target,source,userId){return new ModalBuilder().setCustomId(`sa:submit:${target}:${source}:${userId}`).setTitle(`Apply: ${rank(target).label}`).addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('why').setLabel('Why do you want this rank?').setStyle(TextInputStyle.Paragraph).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('experience').setLabel('Staff/moderation experience').setStyle(TextInputStyle.Paragraph).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('judgment').setLabel('How would you handle a difficult conflict?').setStyle(TextInputStyle.Paragraph).setRequired(true)));
}
async function submitApp(g,userId,target,source,answers){const r=db.prepare('INSERT INTO staff_apps(user_id,target_rank,source,status,answers,created_at) VALUES(?,?,?,?,?,?)').run(userId,target,source,source==='direct'?'interview_ready':'submitted',JSON.stringify(answers),Date.now());const id=Number(r.lastInsertRowid);if(source==='direct'){await createInterview(id,g);return id;}const c=await text(REVIEW);const e=new EmbedBuilder().setTitle(`📥 Application #${id} — ${rank(target).label}`).setDescription(`<@${userId}>\n\n**Why:** ${answers.why}\n\n**Experience:** ${answers.experience}\n\n**Judgment:** ${answers.judgment}`).setFooter({text:'Senior Staff+: approve for interview or deny.'});const msg=await c.send({embeds:[e],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:review:approve:${id}`).setLabel('Approve Interview').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`sa:review:deny:${id}`).setLabel('Deny').setStyle(ButtonStyle.Danger))]});db.prepare('UPDATE staff_apps SET review_message_id=? WHERE id=?').run(msg.id,id);return id;}
const COMMON_QUESTIONS=['What is the main responsibility of your current staff rank?','Why doesn’t a higher rank mean you can do whatever you want?','Explain the difference between legal partial-anarchy gameplay and actual harassment.','Five players accuse someone of X-ray but provide no evidence. What do you do?','You accidentally punish the wrong player. What are your immediate next steps?','Your closest friend on staff is caught abusing permissions. What do you do?','You are personally involved in a serious conflict. Should you investigate and punish the player yourself? Explain.','Why should we promote you instead of waiting?','What is your biggest weakness as a staff member?','If we decide you are not ready today, how would you respond?'];
const SPECIFIC={head_general:['How would you train a new General Staff member who keeps making small moderation mistakes?','When should you bring Senior Staff into a situation?'],senior:['How would you investigate suspected ban evasion?','How would you review an appeal where the original staff member insists their punishment was correct?'],head_senior:['A Senior Staff member issues a major punishment inconsistent with previous cases. What do you do?','When should a situation be escalated to Co-Owner or Owner?'],co_owner:['What factors should be considered before promoting or demoting staff?','A major exploit is damaging the server economy. Explain your response from discovery through resolution.'],owner:['What does having final responsibility for the server mean to you?','What would you do if you realized a major decision YOU made was wrong?'],general:['Why do you want to become General Staff?','What qualities make an excellent staff member?']};
async function createInterview(id,g){const a=appById(id);if(!a)return;const member=await g.members.fetch(a.user_id);const vc=await g.channels.create({name:`Interview — ${member.displayName}`.slice(0,100),type:ChannelType.GuildVoice,parent:APP_CATEGORY,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect]},{id:a.user_id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:HEAD_SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:COOWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:OWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]}]});db.prepare("UPDATE staff_apps SET status='interview_ready',voice_channel_id=? WHERE id=?").run(vc.id,id);const c=await text(INTERVIEW);const qs=[...COMMON_QUESTIONS,...(SPECIFIC[a.target_rank]||[])];await c.send({embeds:[new EmbedBuilder().setTitle(`🎙️ Interview Board #${id}`).setDescription(`**Applicant:** <@${a.user_id}>\n**Target:** ${rank(a.target_rank).label}\n**Voice:** <#${vc.id}>\n\n**Questions**\n${qs.map((q,i)=>`${i+1}. ${q}`).join('\n')}\n\nScore the board out of **100** when finished.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:grade:${id}`).setLabel('Grade & Submit Interview').setStyle(ButtonStyle.Primary))]});}
function gradeModal(id){return new ModalBuilder().setCustomId(`sa:gradeSubmit:${id}`).setTitle(`Grade Interview #${id}`).addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('score').setLabel('Final score / 100').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('notes').setLabel('Board notes / strengths / concerns').setStyle(TextInputStyle.Paragraph).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('announce').setLabel('Announcement date/time (HST)').setPlaceholder('Example: 2026-10-10 18:00').setStyle(TextInputStyle.Short).setRequired(true)));
}
async function postFinal(id){const a=appById(id),c=await text(FINAL);const msg=await c.send({embeds:[new EmbedBuilder().setTitle(`🏆 Final Approval — #${id}`).setDescription(`**Applicant:** <@${a.user_id}>\n**Target:** ${rank(a.target_rank).label}\n**Score:** ${a.score}/100\n**Notes:** ${a.notes}\n**Announcement:** <t:${a.announce_ts}:F>\n\nFinal approval requires **Owner/Co-Owner OR two Senior Staff approvals**.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:final:approve:${id}`).setLabel('Approve').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`sa:final:deny:${id}`).setLabel('Deny').setStyle(ButtonStyle.Danger))]});db.prepare('UPDATE staff_apps SET final_message_id=? WHERE id=?').run(msg.id,id);}
async function finalize(id,g){const a=appById(id),r=rank(a.target_rank),m=await g.members.fetch(a.user_id).catch(()=>null);if(m&&r?.role)await m.roles.add(r.role,'KIND BOSS staff application approved').catch(()=>null);db.prepare("UPDATE staff_apps SET status='approved' WHERE id=?").run(id);const vc=a.voice_channel_id?await g.channels.fetch(a.voice_channel_id).catch(()=>null):null;if(vc)await vc.delete('Interview completed').catch(()=>null);}
async function announceDue(){const now=Math.floor(Date.now()/1000);const rows=db.prepare("SELECT * FROM staff_apps WHERE status='approved' AND announce_ts IS NOT NULL AND announce_ts<=?").all(now);const c=await text(ANNOUNCE);for(const a of rows){if(c)await c.send({embeds:[new EmbedBuilder().setTitle('🎉 Staff Announcement').setDescription(`Congratulations <@${a.user_id}>! They have passed the staff process for **${rank(a.target_rank).label}**.`)]});db.prepare("UPDATE staff_apps SET status='announced' WHERE id=?").run(a.id);}}
client.once(Events.ClientReady,async()=>{await ensureControl().catch(console.error);setInterval(()=>announceDue().catch(console.error),30000);announceDue().catch(console.error);});
client.on(Events.InteractionCreate,async i=>{try{if(!i.guild||i.guild.id!==GUILD_ID)return;const m=await i.guild.members.fetch(i.user.id);
if(i.isButton()&&i.customId==='sa:open'){if(!leadership(m))return eph(i,'❌ Owner/Co-Owner only.');setSetting('open','1');const c=await openPublic(i.guild);await ensureControl();return eph(i,`✅ Applications opened: ${c}`);}
if(i.isButton()&&i.customId==='sa:close'){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');setSetting('open','0');await deletePublic();await ensureControl();return eph(i,'🔴 Applications closed.');}
if(i.isButton()&&i.customId==='sa:direct'){if(!leadership(m))return eph(i,'❌ Owner/Co-Owner only.');return i.reply({content:'Choose the member to interview directly:',components:[new ActionRowBuilder().addComponents(new UserSelectMenuBuilder().setCustomId('sa:directUser').setPlaceholder('Choose member'))],flags:MessageFlags.Ephemeral});}
if(i.isUserSelectMenu()&&i.customId==='sa:directUser'){return i.update({content:`Selected <@${i.values[0]}>. Choose any target rank:`,components:[targetMenu(i.values[0],RANKS.map(r=>r.key),true)]});}
if(i.isButton()&&i.customId==='sa:apply'){if(setting('open')!=='1')return eph(i,'Applications are closed.');const targets=normalTargets(m);if(!targets.length)return eph(i,'You do not currently have an eligible normal promotion path.');return i.reply({content:'Choose the rank you are applying for:',components:[targetMenu(i.user.id,targets,false)],flags:MessageFlags.Ephemeral});}
if(i.isStringSelectMenu()&&i.customId.startsWith('sa:target:')){const [, ,uid,mode]=i.customId.split(':');if(mode==='direct'&&!leadership(m))return eph(i,'❌ Owner/Co-Owner only.');const target=i.values[0];if(mode==='direct'){await submitApp(i.guild,uid,target,'direct',{why:'Direct leadership interview',experience:'Selected by leadership',judgment:'Evaluated during board'});return i.update({content:`✅ Direct interview created for <@${uid}> → **${rank(target).label}**.`,components:[]});}return i.showModal(appModal(target,'normal',uid));}
if(i.isModalSubmit()&&i.customId.startsWith('sa:submit:')){const [, ,target,source,uid]=i.customId.split(':');const id=await submitApp(i.guild,uid,target,source,{why:i.fields.getTextInputValue('why'),experience:i.fields.getTextInputValue('experience'),judgment:i.fields.getTextInputValue('judgment')});return eph(i,`✅ Application #${id} submitted. Senior Staff will review it.`);}
if(i.isButton()&&i.customId.startsWith('sa:review:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const [, ,action,idS]=i.customId.split(':'),id=Number(idS),a=appById(id);if(!a)return eph(i,'Application not found.');if(action==='deny'){db.prepare("UPDATE staff_apps SET status='denied' WHERE id=?").run(id);return i.update({content:`🔴 Application #${id} denied by <@${i.user.id}>.`,embeds:i.message.embeds,components:[]});}await createInterview(id,i.guild);return i.update({content:`✅ Interview approved by <@${i.user.id}>.`,embeds:i.message.embeds,components:[]});}
if(i.isButton()&&i.customId.startsWith('sa:grade:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');return i.showModal(gradeModal(Number(i.customId.split(':')[2])));}
if(i.isModalSubmit()&&i.customId.startsWith('sa:gradeSubmit:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const id=Number(i.customId.split(':')[2]),score=Number(i.fields.getTextInputValue('score'));if(!Number.isInteger(score)||score<0||score>100)return eph(i,'Score must be 0–100.');const dt=DateTime.fromFormat(i.fields.getTextInputValue('announce'),'yyyy-MM-dd HH:mm',{zone:'Pacific/Honolulu'});if(!dt.isValid)return eph(i,'Use announcement format YYYY-MM-DD HH:mm (HST).');db.prepare("UPDATE staff_apps SET score=?,notes=?,announce_ts=?,status='final_review' WHERE id=?").run(score,i.fields.getTextInputValue('notes'),Math.floor(dt.toSeconds()),id);await postFinal(id);return eph(i,'✅ Interview submitted to Final Approval.');}
if(i.isButton()&&i.customId.startsWith('sa:final:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const [, ,action,idS]=i.customId.split(':'),id=Number(idS);if(action==='deny'){db.prepare("UPDATE staff_apps SET status='denied' WHERE id=?").run(id);return i.update({content:`🔴 Final decision: DENIED by <@${i.user.id}>.`,embeds:i.message.embeds,components:[]});}const kind=leadership(m)?'leadership':'senior';db.prepare('INSERT OR IGNORE INTO staff_approvals(app_id,staff_id,role_kind) VALUES(?,?,?)').run(id,i.user.id,kind);const aps=db.prepare('SELECT * FROM staff_approvals WHERE app_id=?').all(id);const ok=aps.some(x=>x.role_kind==='leadership')||aps.filter(x=>x.role_kind==='senior').length>=2;if(ok){await finalize(id,i.guild);return i.update({content:'✅ **FINAL APPROVAL COMPLETE.** Role assigned; announcement queued for the scheduled date.',embeds:i.message.embeds,components:[]});}return eph(i,`✅ Approval recorded. ${aps.filter(x=>x.role_kind==='senior').length}/2 Senior Staff approvals.`);}
}catch(e){console.error('staffApplications interaction error',e);if(i.isRepliable())eph(i,'❌ Something went wrong. Check Railway logs.').catch(()=>{});}});
