const { Events, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle, UserSelectMenuBuilder, StringSelectMenuBuilder, ChannelType, PermissionFlagsBits, MessageFlags } = require('discord.js');
const Database = require('better-sqlite3');
const { DateTime } = require('luxon');
const client = global.__KIND_BOSS_CLIENT;

const GUILD_ID=process.env.GUILD_ID||'1555704317552361563';
const CONTROL=process.env.APPLICATION_CONTROL_CHANNEL_ID, REVIEW=process.env.APPLICATION_REVIEW_CHANNEL_ID, FINAL=process.env.FINAL_APPROVAL_CHANNEL_ID;
const APP_CATEGORY=process.env.STAFF_APPLICATIONS_CATEGORY_ID, COMMUNITY=process.env.COMMUNITY_CATEGORY_ID, ANNOUNCE=process.env.ANNOUNCEMENTS_CHANNEL_ID;
const SMP=process.env.SMP_MEMBER_ROLE_ID, GENERAL=process.env.GENERAL_STAFF_ROLE_ID, HEAD_GENERAL=process.env.HEAD_GENERAL_STAFF_ROLE_ID, SENIOR=process.env.SENIOR_STAFF_ROLE_ID, HEAD_SENIOR=process.env.HEAD_SENIOR_STAFF_ROLE_ID, COOWNER=process.env.CO_OWNER_ROLE_ID, OWNER=process.env.OWNER_ROLE_ID;
const RANKS=[{key:'general',label:'General Staff',role:GENERAL},{key:'head_general',label:'Head of General Staff',role:HEAD_GENERAL},{key:'senior',label:'Senior Staff',role:SENIOR},{key:'head_senior',label:'Head Senior Staff',role:HEAD_SENIOR},{key:'co_owner',label:'Co-Owner',role:COOWNER},{key:'owner',label:'Owner',role:OWNER}];
const db=new Database(process.env.STAFF_APPLICATIONS_DB_PATH||'./data/staff-applications.db');
db.exec(`CREATE TABLE IF NOT EXISTS staff_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS staff_apps(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,target_rank TEXT NOT NULL,source TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'submitted',answers TEXT NOT NULL DEFAULT '{}',score INTEGER,notes TEXT,review_message_id TEXT,voice_channel_id TEXT,final_message_id TEXT,announce_ts INTEGER,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS staff_approvals(app_id INTEGER NOT NULL,staff_id TEXT NOT NULL,role_kind TEXT NOT NULL,PRIMARY KEY(app_id,staff_id));CREATE TABLE IF NOT EXISTS staff_availability(staff_id TEXT PRIMARY KEY,timezone TEXT NOT NULL,windows TEXT NOT NULL,updated_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS interview_approvals(app_id INTEGER NOT NULL,staff_id TEXT NOT NULL,role_kind TEXT NOT NULL,PRIMARY KEY(app_id,staff_id));`);
for(const col of ['private_channel_id TEXT','interview_state TEXT','scheduled_ts INTEGER','interview_text_channel_id TEXT','selected_day TEXT','pending_ts INTEGER']){try{db.exec(`ALTER TABLE staff_apps ADD COLUMN ${col}`)}catch{}}
db.exec(`CREATE TABLE IF NOT EXISTS interview_slot_reservations(ts INTEGER PRIMARY KEY,app_id INTEGER NOT NULL,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL);`);
const setting=(k,d='')=>db.prepare('SELECT value FROM staff_settings WHERE key=?').get(k)?.value??d;
const setSetting=(k,v)=>db.prepare('INSERT INTO staff_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v)); if(!setting('open'))setSetting('open','0');
const appById=id=>db.prepare('SELECT * FROM staff_apps WHERE id=?').get(id), rank=k=>RANKS.find(r=>r.key===k), has=(m,id)=>!!id&&m?.roles?.cache?.has(id), leadership=m=>has(m,OWNER)||has(m,COOWNER), seniorPlus=m=>leadership(m)||has(m,HEAD_SENIOR)||has(m,SENIOR);
const eph=(i,c)=>i.replied||i.deferred?i.followUp({content:c,flags:MessageFlags.Ephemeral}):i.reply({content:c,flags:MessageFlags.Ephemeral});
async function text(id){const c=await client.channels.fetch(id).catch(()=>null);return c?.isTextBased()?c:null;}
function currentRank(m){for(const r of [...RANKS].reverse())if(has(m,r.role))return r.key;return has(m,SMP)?'member':null;}
function normalTargets(m){const c=currentRank(m);if(c==='member')return['general'];if(c==='general')return['head_general','senior'];if(c==='head_general')return['senior'];if(c==='senior')return['head_senior'];if(c==='head_senior')return['co_owner'];if(c==='co_owner')return['owner'];return[];}
function panel(){return new EmbedBuilder().setTitle('🛡️ KIND SMP Staff Applications').setDescription(`**Public applications:** ${setting('open')==='1'?'🟢 Open':'🔴 Closed'}\n\nUse **Direct Interview** for a leadership-selected member. Senior Staff+ should set availability so KIND BOSS can offer interview times automatically.`);}
function panelRows(){return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('sa:open').setLabel('Open Applications').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('sa:close').setLabel('Close Applications').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('sa:direct').setLabel('Direct Interview').setStyle(ButtonStyle.Primary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('sa:availability').setLabel('🗓️ Set Availability').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('sa:myAvailability').setLabel('📅 My Availability').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('sa:availabilityHelp').setLabel('❓ Availability Help').setStyle(ButtonStyle.Secondary))];}
async function ensureControl(){const c=await text(CONTROL);if(!c)return;const ms=await c.messages.fetch({limit:100}).catch(()=>null);const ps=ms?[...ms.values()].filter(m=>m.author?.id===client.user.id&&m.components?.some(r=>r.components?.some(x=>x.customId==='sa:open'))):[];ps.sort((a,b)=>b.createdTimestamp-a.createdTimestamp);for(const d of ps.slice(1))await d.delete().catch(()=>{});return ps[0]?ps[0].edit({embeds:[panel()],components:panelRows()}):c.send({embeds:[panel()],components:panelRows()});}
async function deletePublic(){const id=setting('public_channel');if(id){const c=await client.channels.fetch(id).catch(()=>null);if(c)await c.delete('Staff applications closed').catch(()=>{});}setSetting('public_channel','');}
async function openPublic(g){let c=setting('public_channel')?await g.channels.fetch(setting('public_channel')).catch(()=>null):null;if(!c)c=await g.channels.create({name:'📋・staff-applications',type:ChannelType.GuildText,parent:COMMUNITY,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:SMP,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory],deny:[PermissionFlagsBits.SendMessages]},{id:GENERAL,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory],deny:[PermissionFlagsBits.SendMessages]},{id:SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory],deny:[PermissionFlagsBits.SendMessages]},{id:OWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory]}]});setSetting('public_channel',c.id);await c.send({embeds:[new EmbedBuilder().setTitle('🛡️ Staff Applications Are Open').setDescription('SMP Members may apply for **General Staff**. Existing staff may apply for an eligible higher rank.\n\nA higher rank means more responsibility and trust.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('sa:apply').setLabel('Apply for Staff / Promotion').setStyle(ButtonStyle.Success))]});return c;}
function targetMenu(id,keys,direct=false){return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`sa:target:${id}:${direct?'direct':'normal'}`).setPlaceholder('Choose target rank').addOptions(keys.map(k=>({label:rank(k).label,value:k}))));}
function appModal(target,source,userId){return new ModalBuilder().setCustomId(`sa:submit:${target}:${source}:${userId}`).setTitle(`Apply: ${rank(target).label}`).addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('why').setLabel('Why do you want this rank?').setStyle(TextInputStyle.Paragraph).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('experience').setLabel('Staff/moderation experience').setStyle(TextInputStyle.Paragraph).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('judgment').setLabel('How would you handle a difficult conflict?').setStyle(TextInputStyle.Paragraph).setRequired(true)));}
async function createPrivateChannel(g,userId,target){const member=await g.members.fetch(userId);return g.channels.create({name:`application-${member.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,90),type:ChannelType.GuildText,parent:APP_CATEGORY,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:userId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:HEAD_SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:COOWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:OWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}]});}
function studyGuideEmbed(a){const extras={general:'everyday moderation, evidence, fairness, escalation and calm communication',head_general:'training General Staff, resolving staff disagreements, report organization and escalation',senior:'serious cheating investigations, ban evasion, exploits, appeals and multi-person investigations',head_senior:'reviewing major punishments, Senior Staff disagreements, staff-abuse investigations, difficult appeals and escalation',co_owner:'leadership complaints, intervention, promotions/demotions, major exploits and leadership disagreements',owner:'final responsibility, avoiding micromanagement, infrastructure/security and correcting major decisions'};return new EmbedBuilder().setTitle(`📚 Study Guide — ${rank(a.target_rank).label}`).setDescription(`Prepare for these core areas:\n• Staff knowledge & chain of command\n• Partial-anarchy judgment\n• Evidence & investigations\n• Strikes, jail & punishments\n• Staff integrity\n• Leadership & escalation\n• Emergency judgment\n• Professionalism\n\n🎯 **Rank focus:** ${extras[a.target_rank]||'responsibilities of the target rank'}\n\n💡 Do not memorize scripted answers. Be ready to explain **why** you would make a decision. Exact interview questions are not shown.`);}
function availabilityHelp(){return new EmbedBuilder().setTitle('📅 How to Set Interview Availability').setDescription('**1.** Press **🗓️ Set Availability**.\n**2.** Select the days that share the same hours.\n**3.** Select **From** and **Until** using AM/PM.\n**4.** Select your timezone.\n**5.** Press **➕ Add Availability** to save that group.\n**6.** Change the days/times and press **➕ Add This Group** again for a different schedule.\n**7.** Repeat as many times as needed.\n**8.** Press **💾 Finish & Save All** when done.\n\nExample: Monday/Wednesday/Friday can be **4:00 PM - 8:00 PM**, while Saturday/Sunday can be **12:00 PM - 5:00 PM**. KIND BOSS combines every group when finding times where at least two eligible interviewers overlap.');}
const DAY={sun:7,mon:1,tue:2,wed:3,thu:4,fri:5,sat:6};
const DAY_NAMES=[['mon','Monday'],['tue','Tuesday'],['wed','Wednesday'],['thu','Thursday'],['fri','Friday'],['sat','Saturday'],['sun','Sunday']];
const TZ_OPTIONS=[['Pacific/Honolulu','Hawaii (HST)'],['America/Los_Angeles','Pacific Time'],['America/Denver','Mountain Time'],['America/Chicago','Central Time'],['America/New_York','Eastern Time'],['America/Anchorage','Alaska Time']];
const availabilityDrafts=new Map();
function hourLabel(h){const ap=h<12?'AM':'PM',hr=h%12||12;return `${hr}:00 ${ap}`;}
function blankGroup(){return {days:[],start:null,end:null};}
function getAvailDraft(userId){let d=availabilityDrafts.get(userId);if(!d){d={tz:null,groups:[],editing:blankGroup()};availabilityDrafts.set(userId,d);}return d;}
function groupSummary(g,n){const days=g.days?.length?g.days.map(x=>DAY_NAMES.find(y=>y[0]===x)?.[1]).join(', '):'No days';return `**Group ${n}:** ${days}\n${hourLabel(g.start)} - ${hourLabel(g.end)}`;}
function availabilitySummary(d){const groups=d.groups?.length?d.groups.map((g,n)=>groupSummary(g,n+1)).join('\n\n'):'*No availability groups saved yet.*';const tz=d.tz?TZ_OPTIONS.find(x=>x[0]===d.tz)?.[1]||d.tz:'Not selected';return `${groups}\n\n**Timezone:** ${tz}`;}
function availabilityRows(userId){const d=getAvailDraft(userId),g=d.editing||blankGroup();const dayMenu=new StringSelectMenuBuilder().setCustomId('sa:availDays').setPlaceholder(g.days.length?`${g.days.length} day(s) selected`:'Select days for this availability').setMinValues(1).setMaxValues(7).addOptions(DAY_NAMES.map(([v,l])=>({label:l,value:v,default:g.days.includes(v)})));const timeOpts=Array.from({length:24},(_,h)=>({label:hourLabel(h),value:String(h)}));const start=new StringSelectMenuBuilder().setCustomId('sa:availStart').setPlaceholder(g.start===null?'Available from...':`From ${hourLabel(g.start)}`).addOptions(timeOpts.map(o=>({...o,default:Number(o.value)===g.start})));const end=new StringSelectMenuBuilder().setCustomId('sa:availEnd').setPlaceholder(g.end===null?'Available until...':`Until ${hourLabel(g.end)}`).addOptions(timeOpts.map(o=>({...o,default:Number(o.value)===g.end})));const tz=new StringSelectMenuBuilder().setCustomId('sa:availTz').setPlaceholder(d.tz?TZ_OPTIONS.find(x=>x[0]===d.tz)?.[1]||d.tz:'Select your timezone').addOptions(TZ_OPTIONS.map(([v,l])=>({label:l,value:v,default:d.tz===v})));return [new ActionRowBuilder().addComponents(dayMenu),new ActionRowBuilder().addComponents(start),new ActionRowBuilder().addComponents(end),new ActionRowBuilder().addComponents(tz),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('sa:availAddGroup').setLabel(d.groups.length?'➕ Add This Group':'➕ Add Availability').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('sa:availFinish').setLabel('💾 Finish & Save All').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('sa:availCancel').setLabel('Cancel').setStyle(ButtonStyle.Secondary))];}
function windowsFromGroups(d){return d.groups.flatMap(g=>g.days.map(day=>`${day[0].toUpperCase()+day.slice(1)} ${String(g.start).padStart(2,'0')}:00-${String(g.end).padStart(2,'0')}:00`)).join('\n');}
function displayWindows(tz,raw){const wins=parseWindows(tz,raw)||[];return wins.map(w=>{const day=DAY_NAMES.find(([k])=>DAY[k]===w.weekday)?.[1]||'Day';return `${day}: ${hourLabel(w.sh)} - ${hourLabel(w.eh)}`;}).join('\n');}
function parseWindows(tz,raw){if(!DateTime.now().setZone(tz).isValid)return null;const out=[];for(const line of raw.split(/\n+/).map(x=>x.trim()).filter(Boolean)){const m=line.match(/^(Sun|Mon|Tue|Wed|Thu|Fri|Sat)\s+(\d{1,2}):(\d{2})-(\d{1,2}):(\d{2})$/i);if(!m)return null;const vals=m.slice(2).map(Number);if(vals[0]>23||vals[1]>59||vals[2]>23||vals[3]>59)return null;out.push({weekday:DAY[m[1].toLowerCase()],sh:vals[0],sm:vals[1],eh:vals[2],em:vals[3]});}return out.length?out:null;}
function nextOccurrences(row,days=21){const wins=parseWindows(row.timezone,row.windows)||[], now=DateTime.now().setZone(row.timezone), out=[];for(let d=0;d<days;d++){const date=now.startOf('day').plus({days:d});for(const w of wins)if(date.weekday===w.weekday){const s=date.set({hour:w.sh,minute:w.sm}),e=date.set({hour:w.eh,minute:w.em});if(e>s&&e>now)out.push([s.toUTC(),e.toUTC()]);}}return out;}
async function eligibleAvailabilityRows(guild){const rows=db.prepare('SELECT * FROM staff_availability').all(),out=[];for(const row of rows){const member=await guild.members.fetch(row.staff_id).catch(()=>null);if(!member||!seniorPlus(member))continue;out.push({...row,isLeadership:leadership(member)});}return out;}
async function overlapOptions(guild){const rows=await eligibleAvailabilityRows(guild),slots=[];const addWindow=(start,end,staff,kind)=>{let s=start;while(s.plus({minutes:45})<=end){const ts=Math.floor(s.toSeconds());if(ts>Math.floor(Date.now()/1000)+900)slots.push({ts,staff,kind});s=s.plus({minutes:60});}};
// Owner or Co-Owner can interview/approve by themselves, so their saved availability is immediately selectable.
for(const row of rows.filter(r=>r.isLeadership))for(const w of nextOccurrences(row))addWindow(w[0],w[1],[row.staff_id],'leadership');
// Otherwise, require an overlap between two different Senior Staff interviewers.
const seniors=rows.filter(r=>!r.isLeadership);for(let i=0;i<seniors.length;i++)for(let j=i+1;j<seniors.length;j++)for(const a of nextOccurrences(seniors[i]))for(const b of nextOccurrences(seniors[j])){const start=a[0]>b[0]?a[0]:b[0],end=a[1]<b[1]?a[1]:b[1];if(start<end)addWindow(start,end,[seniors[i].staff_id,seniors[j].staff_id],'two-senior');}
const seen=new Set();return slots.sort((a,b)=>a.ts-b.ts).filter(x=>!seen.has(x.ts)&&(seen.add(x.ts),true)).slice(0,120);}
function clearExpiredReservations(){db.prepare('DELETE FROM interview_slot_reservations WHERE expires_at<=?').run(Math.floor(Date.now()/1000));}
async function availableOptions(id,guild){clearExpiredReservations();const opts=await overlapOptions(guild),reserved=new Set(db.prepare('SELECT ts FROM interview_slot_reservations WHERE app_id<>?').all(id).map(x=>Number(x.ts)));return opts.filter(o=>!reserved.has(o.ts));}
function dayKey(ts){return DateTime.fromSeconds(ts,{zone:'utc'}).setZone('Pacific/Honolulu').toISODate();}
function dayLabel(key){return DateTime.fromISO(key,{zone:'Pacific/Honolulu'}).toFormat('cccc, LLLL d');}
async function dayPicker(id,guild){const opts=await availableOptions(id,guild);if(!opts.length)return null;const days=[];for(const o of opts){const k=dayKey(o.ts);if(!days.includes(k))days.push(k);if(days.length>=7)break;}const menu=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`sa:day:${id}`).setPlaceholder('1️⃣ Choose a day').addOptions(days.map(k=>({label:dayLabel(k),value:k,description:`Available interview times on ${dayLabel(k)}`}))));return {menu,days};}
async function timePicker(id,guild,key){const opts=(await availableOptions(id,guild)).filter(o=>dayKey(o.ts)===key).slice(0,25);if(!opts.length)return null;const menu=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`sa:picktime:${id}`).setPlaceholder('2️⃣ Choose a time').addOptions(opts.map(o=>({label:DateTime.fromSeconds(o.ts,{zone:'utc'}).setZone('Pacific/Honolulu').toFormat('h:mm a'),description:o.kind==='leadership'?'Interview staff available':'Two interview staff available',value:String(o.ts)}))));return {menu,opts};}
function scheduleEmbed(target,extra=''){return new EmbedBuilder().setTitle(`📅 Choose Your Interview Time — ${rank(target).label}`).setDescription(`Pick a **day**, then choose a **time** that works for you.\n\nDiscord will show the final selected time in **your own timezone**.\n\n✅ Only times with enough interview staff are offered.${extra?`\n\n${extra}`:''}`);}
async function schedulePanel(id,guild,target){const d=await dayPicker(id,guild);if(!d)return null;return {embeds:[scheduleEmbed(target)],components:[d.menu,new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:refreshTimes:${id}`).setLabel('🔄 Refresh').setStyle(ButtonStyle.Secondary))]};}
async function reviewPayload(id){const a=appById(id),ans=JSON.parse(a.answers||'{}'),aps=db.prepare('SELECT * FROM interview_approvals WHERE app_id=?').all(id),seniorCount=aps.filter(x=>x.role_kind==='senior').length,lead=aps.find(x=>x.role_kind==='leadership');const approval=lead?`✅ Confirmed by leadership (<@${lead.staff_id}>)`:`${seniorCount>=2?'✅':'🟡'} Senior Staff approvals: **${seniorCount}/2**`;return {embeds:[new EmbedBuilder().setTitle(`📥 Application #${id} — ${rank(a.target_rank).label}`).setDescription(`<@${a.user_id}>\n**Source:** ${a.source==='direct'?'Direct Interview':'Application'}\n\n**Why:** ${ans.why||'-'}\n\n**Experience:** ${ans.experience||'-'}\n\n**Judgment:** ${ans.judgment||'-'}${a.scheduled_ts?`\n\n**Requested interview:** <t:${a.scheduled_ts}:F> (<t:${a.scheduled_ts}:R>)`:''}\n\n**Interview approval:** ${approval}\n\nThe interview is created only after **Owner/Co-Owner approval OR two different Senior Staff approvals**.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:review:approve:${id}`).setLabel('Approve Interview').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`sa:review:reschedule:${id}`).setLabel('Reschedule').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`sa:review:deny:${id}`).setLabel('Deny').setStyle(ButtonStyle.Danger))]};}
async function postReview(id){const a=appById(id),c=await text(REVIEW);if(!c)return;const msg=await c.send(await reviewPayload(id));db.prepare('UPDATE staff_apps SET review_message_id=? WHERE id=?').run(msg.id,id);}
async function makeApplication(g,userId,target,source){const ch=await createPrivateChannel(g,userId,target);const r=db.prepare('INSERT INTO staff_apps(user_id,target_rank,source,status,answers,private_channel_id,created_at) VALUES(?,?,?,?,?,?,?)').run(userId,target,source,'choosing_time','{}',ch.id,Date.now());const id=Number(r.lastInsertRowid),panel=await schedulePanel(id,g,target);if(panel)await ch.send({content:`<@${userId}>`,...panel});else await ch.send({content:`<@${userId}>`,embeds:[new EmbedBuilder().setTitle(`📅 Choose Your Interview Time — ${rank(target).label}`).setDescription('⚠️ **No interview times are available yet.**\n\nA selectable time needs either:\n• an **Owner or Co-Owner** with saved availability, or\n• **two different Senior Staff** whose availability overlaps.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:refreshTimes:${id}`).setLabel('🔄 Refresh Available Times').setStyle(ButtonStyle.Primary))]});return id;}
const CATEGORIES=[
{key:'knowledge',name:'📖 Staff Knowledge',qs:['What is the main responsibility of your current staff rank?','What additional responsibilities would you receive in the target rank?','Explain the KIND SMP staff chain of command.','Why does a higher rank mean more responsibility rather than more freedom?','Give one situation you should handle yourself and one you should escalate.']},
{key:'anarchy',name:'⚔️ Partial-Anarchy Judgment',qs:['Your unprotected base is legally raided. What do you do as staff?','A friend demands restoration after legal theft from an unprotected base. What do you do?','A player repeatedly kills staff in legal PvP. What would you investigate before acting?','Explain legal partial-anarchy gameplay versus harassment.','You dislike a player, but evidence shows no rule was broken. What happens?']},
{key:'evidence',name:'🔎 Evidence & Investigations',qs:['Five players accuse someone of X-ray without evidence. What do you do?','You suspect cheating but cannot prove it. Can you punish? Explain.','A video appears to show hacking. What should you verify first?','A player privately reports a duplication exploit. What do you do with the information?','Why should important evidence and staff actions be documented?']},
{key:'punishment',name:'⚖️ Strikes & Punishments',qs:['Explain the difference between a strike and jail time.','How should repeated small offenses change the punishment?','How should honest cooperation affect a punishment decision?','How should lying, destroying evidence, or framing someone affect your decision?','When should higher staff review a punishment?']},
{key:'integrity',name:'🛡️ Staff Integrity',qs:['Your closest staff friend abuses permissions. What do you do?','You discover staff using spectator to find a hidden base. What do you do?','A staff member spawns survival items for a teammate and asks you to hide it. What do you do?','You punish the wrong player. What are your immediate steps?','Someone publicly accuses you of staff abuse. How do you handle it?']},
{key:'leadership',name:'🧠 Leadership',qs:['Another staff member makes a decision you strongly disagree with. What do you do?','Why should not every small issue go directly to the Owner?','You are personally involved in a serious conflict. Should you investigate it yourself?','How do you help lower staff without taking over everything?','What do you do when higher staff makes a legitimate decision you disagree with?']},
{key:'emergency',name:'🚨 Emergency Judgment',qs:['The server is being crashed while chat spam and arguments happen. What do you handle first and why?','A duplication exploit is actively being abused during another emergency. How do you prioritize it?','After temporarily stopping an emergency, what should happen next?','How do you communicate during a multi-incident emergency?','When should you immediately escalate an emergency to higher leadership?']},
{key:'rank',name:'🎯 Rank-Specific',qs:[]}
];
const SPECIFIC={general:['How would you handle a basic player report fairly?','When should General Staff ask Senior Staff for help?','How would you document a warning or strike?','How do you stay calm when a player is angry?','What should you do when evidence is unclear?'],head_general:['How would you train a General Staff member making small mistakes?','How would you resolve two General Staff disagreeing about a report?','How would you handle a General Staff member repeatedly ignoring evidence?','How would you keep reports organized?','When should you bring Senior Staff into a situation?'],senior:['What changes when handling serious cheating investigations?','How would you investigate suspected ban evasion?','How would you determine exploit versus legitimate gameplay?','How would you review a disputed appeal?','How would you investigate several players and staff without favoritism?'],head_senior:['How would you review an inconsistent major punishment?','How do you resolve Senior Staff disagreement over evidence?','How would you investigate a Senior Staff abuse report?','How would you handle a difficult appeal with conflicting evidence?','When should you escalate to Co-Owner or Owner?'],co_owner:['How would you handle a serious complaint involving Head Staff?','When should you personally intervene in moderation?','What factors matter before promoting or demoting staff?','How would you respond to a major exploit damaging the economy?','How would you resolve a leadership disagreement lower staff cannot resolve?'],owner:['What does final responsibility for the server mean?','How would you avoid micromanaging lower staff?','How do you make a decision when friends disagree but evidence points elsewhere?','How would you protect server security, backups and permissions?','What do you do after realizing a major decision you made was wrong?']};
function state(a){try{return JSON.parse(a.interview_state||'{}')}catch{return{}}}
function saveState(id,s){db.prepare('UPDATE staff_apps SET interview_state=? WHERE id=?').run(JSON.stringify(s),id)}
function catFor(a,idx){const base=CATEGORIES[idx];return {...base,qs:base.key==='rank'?(SPECIFIC[a.target_rank]||SPECIFIC.general):base.qs};}
function boardEmbed(a,s){if(!s.started)return new EmbedBuilder().setTitle(`🎙️ Interview Board #${a.id}`).setDescription(`**Applicant:** <@${a.user_id}>\n**Target:** ${rank(a.target_rank).label}\n**Status:** 🟡 Waiting\n${a.scheduled_ts?`**Scheduled:** <t:${a.scheduled_ts}:F>\n`:''}\nPress **Start Interview** when the applicant and interviewer are ready.`);const idx=s.category||0,cat=catFor(a,idx),sel=s.selected||[];return new EmbedBuilder().setTitle(`${cat.name} — Category ${idx+1}/8`).setDescription(`**Applicant:** <@${a.user_id}> • **Target:** ${rank(a.target_rank).label}\n\nSelect **exactly 3 questions** for this category. Ask them verbally, then grade the category **0/3–3/3**.\n\n${sel.length?`**Selected questions:**\n${sel.map((n,k)=>`${k+1}. ${cat.qs[n]}`).join('\n')}`:'**No questions selected yet.**'}`);}
function boardComponents(a,s){if(!s.started)return[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:startInterview:${a.id}`).setLabel('▶️ Start Interview').setStyle(ButtonStyle.Success))];const idx=s.category||0,cat=catFor(a,idx);if(!(s.selected||[]).length)return[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`sa:questions:${a.id}:${idx}`).setPlaceholder('Select exactly 3 questions').setMinValues(3).setMaxValues(3).addOptions(cat.qs.map((q,n)=>({label:`Question ${n+1}`,description:q.slice(0,95),value:String(n)}))))];return[new ActionRowBuilder().addComponents([0,1,2,3].map(n=>new ButtonBuilder().setCustomId(`sa:catGrade:${a.id}:${n}`).setLabel(`${n}/3`).setStyle(n===3?ButtonStyle.Success:n===0?ButtonStyle.Danger:ButtonStyle.Primary))),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:changeQuestions:${a.id}`).setLabel('Change Questions').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`sa:catNotes:${a.id}`).setLabel('Add Notes').setStyle(ButtonStyle.Secondary))];}
async function createInterview(id,g){let a=appById(id);if(!a)return;const member=await g.members.fetch(a.user_id);const overwrites=[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:a.user_id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:HEAD_SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:COOWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:OWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}];let tc=a.interview_text_channel_id?await g.channels.fetch(a.interview_text_channel_id).catch(()=>null):null;if(!tc)tc=await g.channels.create({name:`interview-${member.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,90),type:ChannelType.GuildText,parent:APP_CATEGORY,permissionOverwrites:overwrites});let vc=a.voice_channel_id?await g.channels.fetch(a.voice_channel_id).catch(()=>null):null;if(!vc)vc=await g.channels.create({name:`Interview — ${member.displayName}`.slice(0,100),type:ChannelType.GuildVoice,parent:APP_CATEGORY,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect]},{id:a.user_id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:HEAD_SENIOR,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:COOWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]},{id:OWNER,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]}]});db.prepare("UPDATE staff_apps SET status='interview_ready',voice_channel_id=?,interview_text_channel_id=? WHERE id=?").run(vc.id,tc.id,id);a=appById(id);const ch=a.private_channel_id?await g.channels.fetch(a.private_channel_id).catch(()=>null):null;if(ch)await ch.send({embeds:[new EmbedBuilder().setTitle('✅ Interview Confirmed').setDescription(`**Position:** ${rank(a.target_rank).label}\n**Interview:** ${a.scheduled_ts?`<t:${a.scheduled_ts}:F> (<t:${a.scheduled_ts}:R>)`:'Time confirmed by staff'}\n**Interview room:** <#${tc.id}>\n**Voice:** <#${vc.id}>`),studyGuideEmbed(a)]});const s={started:false,category:0,grades:{},notes:{}};saveState(id,s);await tc.send({content:`<@${a.user_id}>`,embeds:[boardEmbed(a,s)],components:boardComponents(a,s)});}
function notesModal(id,idx){return new ModalBuilder().setCustomId(`sa:catNotesSubmit:${id}:${idx}`).setTitle('Category Notes').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('notes').setLabel('Interviewer notes (optional)').setStyle(TextInputStyle.Paragraph).setRequired(false)));}
function finishModal(id){return new ModalBuilder().setCustomId(`sa:finishSubmit:${id}`).setTitle(`Finish Interview #${id}`).addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('announce').setLabel('Announcement date/time (HST)').setPlaceholder('2026-10-10 18:00').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('finalnotes').setLabel('Final board notes (optional)').setStyle(TextInputStyle.Paragraph).setRequired(false)));}
async function postFinal(id){const a=appById(id),s=state(a),c=await text(FINAL),grades=s.grades||{},total=Object.values(grades).reduce((x,y)=>x+Number(y||0),0);const lines=CATEGORIES.map((x,i)=>`${x.name}  **${grades[i]??0}/3**`).join('\n');const msg=await c.send({embeds:[new EmbedBuilder().setTitle(`🏆 Interview Results — #${id}`).setDescription(`**Applicant:** <@${a.user_id}>\n**Target:** ${rank(a.target_rank).label}\n\n${lines}\n\n**TOTAL: ${total}/24**\n\n**Final notes:** ${a.notes||'None'}\n**Announcement:** <t:${a.announce_ts}:F>\n\nAwaiting final approval: **Owner/Co-Owner OR two Senior Staff approvals**.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:final:approve:${id}`).setLabel('Approve').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`sa:final:deny:${id}`).setLabel('Deny').setStyle(ButtonStyle.Danger))]});db.prepare('UPDATE staff_apps SET final_message_id=?,score=? WHERE id=?').run(msg.id,total,id);}
async function cleanupInterviewChannels(id,g){const a=appById(id);if(!a)return;const tc=a.interview_text_channel_id?await g.channels.fetch(a.interview_text_channel_id).catch(()=>null):null;const vc=a.voice_channel_id?await g.channels.fetch(a.voice_channel_id).catch(()=>null):null;if(vc)await vc.delete('Interview finished; results posted').catch(()=>{});if(tc)await tc.delete('Interview finished; results posted').catch(()=>{});db.prepare('UPDATE staff_apps SET interview_text_channel_id=NULL,voice_channel_id=NULL WHERE id=?').run(id);}
async function finalize(id,g){const a=appById(id),r=rank(a.target_rank),m=await g.members.fetch(a.user_id).catch(()=>null);if(m&&r?.role)await m.roles.add(r.role,'KIND BOSS staff application approved').catch(()=>{});db.prepare("UPDATE staff_apps SET status='approved' WHERE id=?").run(id);}
async function announceDue(){const now=Math.floor(Date.now()/1000),rows=db.prepare("SELECT * FROM staff_apps WHERE status='approved' AND announce_ts IS NOT NULL AND announce_ts<=?").all(now),c=await text(ANNOUNCE);for(const a of rows){if(c)await c.send({embeds:[new EmbedBuilder().setTitle('🎉 Staff Announcement').setDescription(`Congratulations <@${a.user_id}>! They have passed the staff process for **${rank(a.target_rank).label}**.`)]});db.prepare("UPDATE staff_apps SET status='announced' WHERE id=?").run(a.id);}}
client.once(Events.ClientReady,async()=>{console.log(`✅ Staff Applications ready for guild ${GUILD_ID}.`);await ensureControl().catch(e=>console.error('staffApplications startup error',e));setInterval(()=>announceDue().catch(e=>console.error('staffApplications announce error',e)),30000);announceDue().catch(()=>{});});
client.on(Events.InteractionCreate,async i=>{try{if(!i.guild||typeof i.customId!=='string'||!i.customId.startsWith('sa:'))return;console.log(`[Staff Applications] ${i.user.tag} -> ${i.customId}`);if(i.guild.id!==GUILD_ID)return eph(i,'❌ This panel belongs to a different server.');const m=await i.guild.members.fetch(i.user.id);
if(i.isButton()&&i.customId==='sa:open'){if(!leadership(m))return eph(i,'❌ Owner/Co-Owner only.');setSetting('open','1');const c=await openPublic(i.guild);await ensureControl();return eph(i,`✅ Applications opened: ${c}`);}
if(i.isButton()&&i.customId==='sa:close'){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');setSetting('open','0');await deletePublic();await ensureControl();return eph(i,'🔴 Applications closed.');}
if(i.isButton()&&i.customId==='sa:availabilityHelp')return i.reply({embeds:[availabilityHelp()],flags:MessageFlags.Ephemeral});
if(i.isButton()&&i.customId==='sa:availability'){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const old=db.prepare('SELECT * FROM staff_availability WHERE staff_id=?').get(i.user.id);let d={tz:old?.timezone||null,groups:[],editing:blankGroup()};if(old){const parsed=parseWindows(old.timezone,old.windows)||[];for(const w of parsed){const key=DAY_NAMES.find(([k])=>DAY[k]===w.weekday)?.[0];let g=d.groups.find(x=>x.start===w.sh&&x.end===w.eh);if(!g){g={days:[],start:w.sh,end:w.eh};d.groups.push(g);}if(key)g.days.push(key);}}availabilityDrafts.set(i.user.id,d);return i.reply({content:`🗓️ **Set Interview Availability**\nCreate one group for days that share the same hours. Then use **➕ Add This Group** for another schedule.\n\n${availabilitySummary(d)}`,components:availabilityRows(i.user.id),flags:MessageFlags.Ephemeral});}
if(i.isStringSelectMenu()&&['sa:availDays','sa:availStart','sa:availEnd','sa:availTz'].includes(i.customId)){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const d=getAvailDraft(i.user.id),g=d.editing;if(i.customId==='sa:availDays')g.days=i.values;if(i.customId==='sa:availStart')g.start=Number(i.values[0]);if(i.customId==='sa:availEnd')g.end=Number(i.values[0]);if(i.customId==='sa:availTz')d.tz=i.values[0];return i.update({content:`🗓️ **Set Interview Availability**\nAdd each different day/time schedule as its own group.\n\n${availabilitySummary(d)}`,components:availabilityRows(i.user.id)});}
if(i.isButton()&&i.customId==='sa:availAddGroup'){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const d=getAvailDraft(i.user.id),g=d.editing;if(!g.days.length||g.start===null||g.end===null||!d.tz)return eph(i,'❌ Select days, start time, end time, and timezone first.');if(g.end<=g.start)return eph(i,'❌ Ending time must be later than starting time.');d.groups.push({days:[...g.days],start:g.start,end:g.end});d.editing=blankGroup();return i.update({content:`✅ **Availability group added.**\nNow select another set of days/times, or press **💾 Finish & Save All**.\n\n${availabilitySummary(d)}`,components:availabilityRows(i.user.id)});}
if(i.isButton()&&i.customId==='sa:availCancel'){availabilityDrafts.delete(i.user.id);return i.update({content:'Cancelled. Your saved availability was not changed.',components:[]});}
if(i.isButton()&&i.customId==='sa:availFinish'){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const d=getAvailDraft(i.user.id);if(!d.groups.length)return eph(i,'❌ Add at least one availability group first.');if(!d.tz)return eph(i,'❌ Select your timezone first.');const wins=windowsFromGroups(d);db.prepare('INSERT INTO staff_availability(staff_id,timezone,windows,updated_at) VALUES(?,?,?,?) ON CONFLICT(staff_id) DO UPDATE SET timezone=excluded.timezone,windows=excluded.windows,updated_at=excluded.updated_at').run(i.user.id,d.tz,wins,Date.now());const summary=availabilitySummary(d);availabilityDrafts.delete(i.user.id);return i.update({content:`✅ **All availability saved**\n\n${summary}`,components:[]});}
if(i.isButton()&&i.customId==='sa:myAvailability'){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const a=db.prepare('SELECT * FROM staff_availability WHERE staff_id=?').get(i.user.id);const tzLabel=a?(TZ_OPTIONS.find(x=>x[0]===a.timezone)?.[1]||a.timezone):'';return eph(i,a?`📅 **Your availability**\n**Timezone:** ${tzLabel}\n${displayWindows(a.timezone,a.windows)}`:'You have not set availability yet. Press **Set Availability**.');}
if(i.isButton()&&i.customId==='sa:direct'){if(!leadership(m))return eph(i,'❌ Owner/Co-Owner only.');return i.reply({content:'Choose the member to invite to a Direct Interview:',components:[new ActionRowBuilder().addComponents(new UserSelectMenuBuilder().setCustomId('sa:directUser').setPlaceholder('Choose member'))],flags:MessageFlags.Ephemeral});}
if(i.isUserSelectMenu()&&i.customId==='sa:directUser')return i.update({content:`Selected <@${i.values[0]}>. Choose the target rank:`,components:[targetMenu(i.values[0],RANKS.map(r=>r.key),true)]});
if(i.isButton()&&i.customId==='sa:apply'){if(setting('open')!=='1')return eph(i,'Applications are closed.');const t=normalTargets(m);if(!t.length)return eph(i,'You do not have an eligible promotion path.');return i.reply({content:'Choose the rank you are applying for:',components:[targetMenu(i.user.id,t,false)],flags:MessageFlags.Ephemeral});}
if(i.isStringSelectMenu()&&i.customId.startsWith('sa:target:')){const [, ,uid,mode]=i.customId.split(':');if(mode==='direct'&&!leadership(m))return eph(i,'❌ Owner/Co-Owner only.');const id=await makeApplication(i.guild,uid,i.values[0],mode==='direct'?'direct':'normal');return i.update({content:`✅ Private application channel created: <#${appById(id).private_channel_id}>`,components:[]});}
if(i.isButton()&&i.customId.startsWith('sa:refreshTimes:')){const id=Number(i.customId.split(':')[2]),a=appById(id);if(!a||i.user.id!==a.user_id)return eph(i,'❌ This application is not yours.');const p=await schedulePanel(id,i.guild,a.target_rank);if(!p)return eph(i,'⚠️ No interview times are available yet.');db.prepare('UPDATE staff_apps SET selected_day=NULL,pending_ts=NULL WHERE id=?').run(id);return i.update(p);}
if(i.isStringSelectMenu()&&i.customId.startsWith('sa:day:')){const id=Number(i.customId.split(':')[2]),a=appById(id);if(!a||i.user.id!==a.user_id)return eph(i,'❌ This application is not yours.');if(!['choosing_time','rescheduling'].includes(a.status))return eph(i,'❌ Interview time selection is closed.');const key=i.values[0],tp=await timePicker(id,i.guild,key);if(!tp)return eph(i,'⚠️ Those times were just taken. Choose another day.');db.prepare('UPDATE staff_apps SET selected_day=?,pending_ts=NULL WHERE id=?').run(key,id);const d=await dayPicker(id,i.guild);return i.update({embeds:[scheduleEmbed(a.target_rank,`**Selected day:** ${dayLabel(key)}\nNow choose a time below.`)],components:[d.menu,tp.menu,new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:refreshTimes:${id}`).setLabel('← Change / Refresh').setStyle(ButtonStyle.Secondary))]});}
if(i.isStringSelectMenu()&&i.customId.startsWith('sa:picktime:')){const id=Number(i.customId.split(':')[2]),a=appById(id);if(!a||i.user.id!==a.user_id)return eph(i,'❌ This application is not yours.');const ts=Number(i.values[0]),valid=(await availableOptions(id,i.guild)).some(o=>o.ts===ts);if(!valid)return eph(i,'⚠️ That time is no longer available. Please refresh and choose another.');db.prepare('UPDATE staff_apps SET pending_ts=? WHERE id=?').run(ts,id);return i.update({embeds:[new EmbedBuilder().setTitle('🗓️ Confirm Your Interview Time').setDescription(`**Selected:** <t:${ts}:F>\n**Your local time:** <t:${ts}:t>\n**Starts:** <t:${ts}:R>\n\n👥 **Interview staff available**\n✅ This slot can be requested.\n\nPress **Confirm Interview Time** to reserve it while you complete your application.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:confirmTime:${id}`).setLabel('✅ Confirm Interview Time').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`sa:refreshTimes:${id}`).setLabel('← Change Time').setStyle(ButtonStyle.Secondary))]});}
if(i.isButton()&&i.customId.startsWith('sa:confirmTime:')){const id=Number(i.customId.split(':')[2]),a=appById(id);if(!a||i.user.id!==a.user_id)return eph(i,'❌ This application is not yours.');const ts=Number(a.pending_ts);if(!ts)return eph(i,'❌ Choose a time first.');clearExpiredReservations();const taken=db.prepare('SELECT * FROM interview_slot_reservations WHERE ts=? AND app_id<>?').get(ts,id);if(taken)return eph(i,'⚠️ Someone else just reserved that time. Press **Change Time** and choose another.');db.prepare('DELETE FROM interview_slot_reservations WHERE app_id=?').run(id);db.prepare('INSERT OR REPLACE INTO interview_slot_reservations(ts,app_id,user_id,expires_at) VALUES(?,?,?,?)').run(ts,id,a.user_id,Math.floor(Date.now()/1000)+900);db.prepare("UPDATE staff_apps SET scheduled_ts=?,status='awaiting_form' WHERE id=?").run(ts,id);return i.update({embeds:[new EmbedBuilder().setTitle('✅ Interview Time Reserved').setDescription(`Your requested interview time is **<t:${ts}:F>** (<t:${ts}:R>).\n\n⏳ This slot is reserved for **15 minutes** while you complete the application.\n\nNow continue to the application form.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:privateForm:${id}`).setLabel('📝 Continue to Application').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`sa:changeReserved:${id}`).setLabel('← Change Time').setStyle(ButtonStyle.Secondary))]});}
if(i.isButton()&&i.customId.startsWith('sa:changeReserved:')){const id=Number(i.customId.split(':')[2]),a=appById(id);if(!a||i.user.id!==a.user_id)return eph(i,'❌ This application is not yours.');db.prepare('DELETE FROM interview_slot_reservations WHERE app_id=?').run(id);db.prepare("UPDATE staff_apps SET scheduled_ts=NULL,pending_ts=NULL,selected_day=NULL,status='choosing_time' WHERE id=?").run(id);const p=await schedulePanel(id,i.guild,a.target_rank);return p?i.update(p):eph(i,'⚠️ No interview times are available right now.');}
if(i.isButton()&&i.customId.startsWith('sa:privateForm:')){const id=Number(i.customId.split(':')[2]),a=appById(id);if(!a||i.user.id!==a.user_id)return eph(i,'❌ This application is not yours.');if(!a.scheduled_ts)return eph(i,'❌ Choose an interview time first.');if(a.status!=='awaiting_form')return eph(i,'❌ This application form is not ready.');return i.showModal(appModal(a.target_rank,a.source,a.user_id));}
if(i.isModalSubmit()&&i.customId.startsWith('sa:submit:')){const [, ,target,source,uid]=i.customId.split(':'),a=db.prepare("SELECT * FROM staff_apps WHERE user_id=? AND target_rank=? AND source=? AND status='awaiting_form' ORDER BY id DESC LIMIT 1").get(uid,target,source);if(!a)return eph(i,'Application session not found.');const answers={why:i.fields.getTextInputValue('why'),experience:i.fields.getTextInputValue('experience'),judgment:i.fields.getTextInputValue('judgment')};db.prepare("UPDATE staff_apps SET answers=?,status='submitted' WHERE id=?").run(JSON.stringify(answers),a.id);db.prepare('DELETE FROM interview_slot_reservations WHERE app_id=?').run(a.id);await postReview(a.id);const ch=await i.guild.channels.fetch(a.private_channel_id).catch(()=>null);if(ch)await ch.send({embeds:[new EmbedBuilder().setTitle('✅ Application Submitted').setDescription(`Your application and interview request were submitted together.\n\n**Requested interview:** <t:${a.scheduled_ts}:F> (<t:${a.scheduled_ts}:R>)\n\nIt now needs **Owner approval**, **Co-Owner approval**, or approvals from **two different Senior Staff**.`)]});return eph(i,'✅ Application submitted with your selected interview time.');}
if(i.isStringSelectMenu()&&i.customId.startsWith('sa:time:'))return eph(i,'🔄 This is an old scheduling menu. Please start a new application to use the improved day/time picker.');
if(i.isButton()&&i.customId.startsWith('sa:requestTime:'))return eph(i,'📝 Please message staff in this private application channel with times that work for you. Staff can update availability and offer new overlapping options.');
if(i.isButton()&&i.customId.startsWith('sa:review:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const [, ,action,idS]=i.customId.split(':'),id=Number(idS),a=appById(id);if(!a)return eph(i,'Application not found.');if(action==='deny'){db.prepare("UPDATE staff_apps SET status='denied' WHERE id=?").run(id);return i.update({content:`🔴 Application #${id} denied by <@${i.user.id}>.`,embeds:i.message.embeds,components:[]});}if(action==='reschedule'){db.prepare('DELETE FROM interview_approvals WHERE app_id=?').run(id);db.prepare("UPDATE staff_apps SET status='rescheduling' WHERE id=?").run(id);const ch=await i.guild.channels.fetch(a.private_channel_id).catch(()=>null),p=await schedulePanel(id,i.guild,a.target_rank);if(ch&&p)await ch.send({content:`<@${a.user_id}>`,...p});return eph(i,p?'✅ New day/time picker sent to the applicant. Interview approvals were reset.':'⚠️ No interview times are available. Add Owner/Co-Owner availability or overlapping availability from two Senior Staff.');}const kind=leadership(m)?'leadership':'senior';db.prepare('INSERT OR IGNORE INTO interview_approvals(app_id,staff_id,role_kind) VALUES(?,?,?)').run(id,i.user.id,kind);const aps=db.prepare('SELECT * FROM interview_approvals WHERE app_id=?').all(id),seniorCount=aps.filter(x=>x.role_kind==='senior').length,ok=aps.some(x=>x.role_kind==='leadership')||seniorCount>=2;if(ok){db.prepare("UPDATE staff_apps SET status='interview_confirmed' WHERE id=?").run(id);await i.update(await reviewPayload(id));const ch=await i.guild.channels.fetch(a.private_channel_id).catch(()=>null);if(ch)await ch.send({embeds:[new EmbedBuilder().setTitle('✅ Interview Time Approved').setDescription(`Your interview for **${rank(a.target_rank).label}** is confirmed for <t:${a.scheduled_ts}:F> (<t:${a.scheduled_ts}:R>).\n\nYour study guide is below.`),studyGuideEmbed(a)]});await createInterview(id,i.guild);return;}await i.update(await reviewPayload(id));return eph(i,`✅ Your approval was recorded. **${seniorCount}/2 Senior Staff approvals** are currently recorded.`);}
if(i.isButton()&&i.customId.startsWith('sa:startInterview:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const id=Number(i.customId.split(':')[2]),a=appById(id),s=state(a);s.started=true;s.category=0;s.grades=s.grades||{};s.notes=s.notes||{};s.selected=[];saveState(id,s);return i.update({embeds:[boardEmbed(appById(id),s)],components:boardComponents(appById(id),s)});}
if(i.isStringSelectMenu()&&i.customId.startsWith('sa:questions:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const [, ,idS,idxS]=i.customId.split(':'),id=Number(idS),a=appById(id),s=state(a);s.category=Number(idxS);s.selected=i.values.map(Number);saveState(id,s);return i.update({embeds:[boardEmbed(a,s)],components:boardComponents(a,s)});}
if(i.isButton()&&i.customId.startsWith('sa:changeQuestions:')){const id=Number(i.customId.split(':')[2]),a=appById(id),s=state(a);s.selected=[];saveState(id,s);return i.update({embeds:[boardEmbed(a,s)],components:boardComponents(a,s)});}
if(i.isButton()&&i.customId.startsWith('sa:catNotes:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const id=Number(i.customId.split(':')[2]),a=appById(id),s=state(a);return i.showModal(notesModal(id,s.category||0));}
if(i.isModalSubmit()&&i.customId.startsWith('sa:catNotesSubmit:')){const [, ,idS,idxS]=i.customId.split(':'),id=Number(idS),a=appById(id),s=state(a);s.notes=s.notes||{};s.notes[idxS]=i.fields.getTextInputValue('notes');saveState(id,s);return eph(i,'✅ Category notes saved.');}
if(i.isButton()&&i.customId.startsWith('sa:catGrade:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const [, ,idS,gradeS]=i.customId.split(':'),id=Number(idS),a=appById(id),s=state(a),idx=s.category||0;if((s.selected||[]).length!==3)return eph(i,'Select exactly 3 questions first.');s.grades=s.grades||{};s.grades[idx]=Number(gradeS);s.selected=[];if(idx<7){s.category=idx+1;saveState(id,s);return i.update({embeds:[boardEmbed(a,s)],components:boardComponents(a,s)});}saveState(id,s);return i.update({embeds:[new EmbedBuilder().setTitle('🏁 All Categories Graded').setDescription(`All 8 categories are complete.\n\n**Current total: ${Object.values(s.grades).reduce((x,y)=>x+Number(y||0),0)}/24**\n\nPress **Finish Interview** to lock the results and send them to Final Approval.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`sa:finishInterview:${id}`).setLabel('🏁 Finish Interview').setStyle(ButtonStyle.Success))]});}
if(i.isButton()&&i.customId.startsWith('sa:finishInterview:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');return i.showModal(finishModal(Number(i.customId.split(':')[2])));}
if(i.isModalSubmit()&&i.customId.startsWith('sa:finishSubmit:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const id=Number(i.customId.split(':')[2]),a=appById(id),s=state(a);if(Object.keys(s.grades||{}).length<8)return eph(i,'❌ All 8 categories must be graded first.');const dt=DateTime.fromFormat(i.fields.getTextInputValue('announce'),'yyyy-MM-dd HH:mm',{zone:'Pacific/Honolulu'});if(!dt.isValid)return eph(i,'Use YYYY-MM-DD HH:mm (HST).');db.prepare("UPDATE staff_apps SET notes=?,announce_ts=?,status='final_review' WHERE id=?").run(i.fields.getTextInputValue('finalnotes')||'None',Math.floor(dt.toSeconds()),id);await postFinal(id);await eph(i,'✅ Interview locked and sent to Final Approval. This temporary interview room will now be deleted.');await cleanupInterviewChannels(id,i.guild);return;}
if(i.isButton()&&i.customId.startsWith('sa:final:')){if(!seniorPlus(m))return eph(i,'❌ Senior Staff+ only.');const [, ,action,idS]=i.customId.split(':'),id=Number(idS);if(action==='deny'){db.prepare("UPDATE staff_apps SET status='denied' WHERE id=?").run(id);return i.update({content:`🔴 Final decision: DENIED by <@${i.user.id}>.`,embeds:i.message.embeds,components:[]});}const kind=leadership(m)?'leadership':'senior';db.prepare('INSERT OR IGNORE INTO staff_approvals(app_id,staff_id,role_kind) VALUES(?,?,?)').run(id,i.user.id,kind);const aps=db.prepare('SELECT * FROM staff_approvals WHERE app_id=?').all(id),ok=aps.some(x=>x.role_kind==='leadership')||aps.filter(x=>x.role_kind==='senior').length>=2;if(ok){await finalize(id,i.guild);return i.update({content:'✅ **FINAL APPROVAL COMPLETE.** Role assigned; announcement queued.',embeds:i.message.embeds,components:[]});}return eph(i,`✅ Approval recorded. ${aps.filter(x=>x.role_kind==='senior').length}/2 Senior Staff approvals.`);}
}catch(e){console.error('staffApplications interaction error',e);if(i.isRepliable())eph(i,'❌ Something went wrong. Check Railway logs.').catch(()=>{});}});
